#!/usr/bin/env groovy

pipelineJob('job1') {
    displayName('bla bla')

    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url('https://github.com/tom-code/jenkinkstest.git')
                    }
                    branches('*/master')
                }
            }
            scriptPath('pipeline')
        }
    }
}
queue('job1')
listView('mojeee') {
    jobs {
        name('job1')
    }
}
